services:
  ollama-chat:
    build: .
    container_name: ollama-chat
    ports:
      - '3000:3000'
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - SEARXNG_HOST=http://searxng:8080
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
    depends_on:
      - searxng
    networks:
      - neural-net

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - '8080:8080'
    volumes:
      - ./searxng:/etc/searxng
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080
    restart: unless-stopped
    networks:
      - neural-net

networks:
  neural-net:
    driver: bridge
